### ISSUE TITLE
LinkError: WebAssembly Instantiation: Import #0 module="env" function="memcpy" error: function import requires a callable

### ISSUE THREAD

**Issue by masonforest** [fitzgen/wee_alloc#28]
### Summary

When using wee_alloc and modifying a vec it looks like an external call to `memcpy` is being made. If that's not defined you get the error shown below. I tried manually defining memcpy [here](https://github.com/masonforest/wee_alloc_memcpy_bug/blob/master/run.js#L7-L9) but then I get `RuntimeError: unreachable`.

### Steps to Reproduce

* `git clone https://github.com/masonforest/wee_alloc_memcpy_bug`
* `cd wee_alloc_memcpy_bug`
* `cargo rustc --target wasm32-unknown-unknown --lib -- -O && node run.js`

### Actual Results

```
   Compiling wee_alloc_memcpy_bug v0.1.0 (file:///Users/masonf/src/wee_alloc_memcpy_bug)
    Finished dev [unoptimized + debuginfo] target(s) in 0.52 secs
(node:98141) UnhandledPromiseRejectionWarning: LinkError: WebAssembly Instantiation: Import #0 module="env" function="memcpy" error: function import requires a callable
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
(node:98141) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:98141) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected Results

````
   Compiling wee_alloc_memcpy_bug v0.1.0 (file:///Users/masonf/src/wee_alloc_memcpy_bug)
    Finished dev [unoptimized + debuginfo] target(s) in 0.37 secs
````

**Comment by pepyakin** [comment]
Hi! As a workaround, you can try to add [rlibc](https://github.com/alexcrichton/rlibc) to your project.

**Comment by masonforest** [comment]
That worked! 🎉

Thanks @pepyakin!
